apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::614050726433:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-CJJ5NK9LWK30
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-05-18T14:53:30Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "864"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 5e9396f9-b1f6-4f0c-a0e5-6484d2897a1f
